import { useState, type FormEvent } from 'react'
import { generateResponse } from '../services/ai'

type Status = 'idle' | 'loading' | 'success' | 'error'

export default function AIPlayground() {
  const [prompt, setPrompt] = useState('')
  const [response, setResponse] = useState('')
  const [status, setStatus] = useState<Status>('idle')
  const [error, setError] = useState('')

  const canSubmit = prompt.trim().length > 0 && status !== 'loading'

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!canSubmit) return

    setStatus('loading')
    setError('')
    setResponse('')
    try {
      const result = await generateResponse(prompt.trim())
      setResponse(result.response)
      setStatus('success')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unable to reach the AI service.')
      setStatus('error')
    }
  }

  return (
    <section className="ai-playground">
      <div className="section-header">
        <h2>AI Playground</h2>
        <p>
          Ask DevDocs AI a technical question. Responses are generated by the Grok
          provider on the backend.
        </p>
      </div>

      <form className="playground-form" onSubmit={handleSubmit}>
        <label htmlFor="ai-prompt">Prompt</label>
        <textarea
          id="ai-prompt"
          value={prompt}
          onChange={(event) => setPrompt(event.target.value)}
          placeholder="Explain how FastAPI dependency injection works."
          rows={5}
        />
        <div className="playground-actions">
          <button type="submit" disabled={!canSubmit}>
            {status === 'loading' ? 'Asking Grok...' : 'Ask Grok'}
          </button>
        </div>
      </form>

      {status === 'error' && (
        <div className="error-panel" role="alert">
          {error}
        </div>
      )}

      {status === 'success' && (
        <div className="response-panel">
          <h3>Response</h3>
          <pre>{response}</pre>
        </div>
      )}
    </section>
  )
}
