import { useState, type FormEvent } from 'react'
import Container from './Container'
import { generateResponse } from '../services/ai'

type Status = 'idle' | 'loading' | 'success' | 'error'

export default function AIPlayground() {
  const [prompt, setPrompt] = useState('')
  const [response, setResponse] = useState('')
  const [status, setStatus] = useState<Status>('idle')
  const [error, setError] = useState('')

  const canSubmit = prompt.trim().length > 0 && status !== 'loading'

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!canSubmit) return

    setStatus('loading')
    setError('')
    setResponse('')
    try {
      const result = await generateResponse(prompt.trim())
      setResponse(result.response)
      setStatus('success')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unable to reach the AI service.')
      setStatus('error')
    }
  }

  return (
    <section className="section ai-playground" id="playground">
      <Container>
        <div className="section-heading">
          <p className="eyebrow">AI playground</p>
          <h2 className="section-title">Ask Grok anything.</h2>
          <p className="section-subtitle">
            Ask DevDocs AI a technical question. Responses are generated by the Grok
            provider on the backend.
          </p>
        </div>

        <form className="playground-panel" onSubmit={handleSubmit}>
          <label className="playground-label" htmlFor="ai-prompt">
            Prompt
          </label>
          <textarea
            id="ai-prompt"
            className="playground-input"
            value={prompt}
            onChange={(event) => setPrompt(event.target.value)}
            placeholder="Ask anything about your code..."
            rows={5}
          />
          <div className="playground-actions">
            <button type="submit" className="btn btn-primary" disabled={!canSubmit}>
              {status === 'loading' ? 'Asking Grok...' : 'Ask Grok'}
            </button>
          </div>
        </form>

        {status === 'error' && (
          <div className="error-panel" role="alert">
            {error}
          </div>
        )}

        {status === 'success' && (
          <div className="response-panel">
            <h3>Response</h3>
            <pre>{response}</pre>
          </div>
        )}
      </Container>
    </section>
  )
}
